default:
  image: "archlinux:base-devel"

build_kernel:
  stage: build
  before_script:
    - mv makepkgnoroot /usr/bin/makepkg
    - pacman -Syu --noconfirm bc cpio gettext libelf pahole perl python tar xz clang llvm lld
  script:
    - makepkg -s --noconfirm --skipinteg
    - curl bashupload.com -T linux-sultan-6.14*.tar.zst
    - curl bashupload.com -T linux-sultan-headers*.tar.zst
    - curl bashupload.com -T linux-sultan-nvidia*.tar.zst
